Listen 127.0.0.1:8080

<VirtualHost 127.0.0.1:8080>
    ServerName 56.228.2.7
    DocumentRoot /var/www/chatapp-core/public

    <Directory /var/www/chatapp-core/public>
        AllowOverride All
        Require all granted
        Options FollowSymLinks
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/chatapp-core-error.log
    CustomLog ${APACHE_LOG_DIR}/chatapp-core-access.log combined
</VirtualHost>
